### ISSUE TITLE
clipboard is not working

### ISSUE THREAD

**Issue by MrAlekhin** [shrpne/clipbrd#1] opened 2019-07-17 22:39 UTC
could you please add `el.style.zIndex = 10000;` that works.

**Comment by shrpne** [comment] 2019-07-20 20:59
Hi! Thank you for reach out.

Can you please provide a minimal test case so I can investigate it?
For now, I'm not sure that this fix should be landed and applied for all users, because there is a chance that this issue is specific and caused by a specific environment which can be fixed by fixing the environment.

**Closed as completed** 2020-10-23 00:23 UTC
